# Generated by Django 4.2.13 on 2024-05-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_project_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Projects',
        ),
    ]
