# Generated by Django 4.2.13 on 2024-05-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='featured_image_autor',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Nombre del Autor de la Imagen Destacada'),
        ),
        migrations.AddField(
            model_name='blogentry',
            name='featured_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de la Imagen Destacada'),
        ),
    ]
