# Generated by Django 4.2.13 on 2024-05-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogentry_featured_image_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='featured_image_autor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Autor de la Imagen Destacada'),
        ),
    ]
